<a href="https://colab.research.google.com/github/rizkiar00/Bagging-Berbasis-Naive-Bayes/blob/master/Bagging.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [247]:
!git clone https://github.com/rizkiar00/Bagging-Berbasis-Naive-Bayes

fatal: destination path 'Bagging-Berbasis-Naive-Bayes' already exists and is not an empty directory.


In [0]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt; 
from sklearn.naive_bayes import GaussianNB
from sklearn.model_selection import train_test_split
%matplotlib inline

In [249]:
train = np.genfromtxt('Bagging-Berbasis-Naive-Bayes/TrainsetTugas4ML.csv', delimiter=',', skip_header=1)
dftrain = pd.DataFrame(data=train)
print("Kelas:", pd.Series(dftrain.loc[:,2], name='A').unique())
dftrain


Kelas: [2. 1.]


0      1    2
0     0.75  15.60  2.0
1     0.85  17.45  2.0
2     2.90  21.15  2.0
3     3.10  21.85  2.0
4     3.40  19.70  2.0
5     4.05  18.75  2.0
6     4.40  20.05  2.0
7     4.55  23.90  2.0
8     4.90  15.65  2.0
9     5.10  17.90  2.0
10    5.10  24.40  2.0
11    5.25  14.20  2.0
12    5.35  15.85  2.0
13    5.50  21.80  2.0
14    5.85  20.55  2.0
15    6.05  22.30  2.0
16    6.55  21.80  2.0
17    7.10  18.65  2.0
18    7.20  14.50  2.0
19    7.65  16.50  2.0
20    8.10  26.35  2.0
21    9.20  21.10  2.0
22   10.15  27.70  2.0
23   11.20  22.80  2.0
24   12.15  21.45  2.0
25   12.20  20.90  2.0
26   12.45  27.55  2.0
27   12.60  23.10  2.0
28   13.15  21.85  2.0
29   13.25  23.50  2.0
..     ...    ...  ...
268  38.15   9.70  1.0
269  38.25  17.35  1.0
270  38.30  14.60  1.0
271  38.35  14.35  1.0
272  38.40   9.45  1.0
273  38.50  12.20  1.0
274  38.50  14.25  1.0
275  38.75  16.85  1.0
276  38.85  15.50  1.0
277  38.95  12.90  1.0
278  39.00  13.20  1.0
279  39.00  16.60  1.0
280  39.20  12.35  1.0
281  39.25  15.50  1.0
282  39.50  11.80  1.0
283  39.50  16.95  1.0
284  39.65  16.20  1.0
285  39.75  12.75  1.0
286  39.90  16.20  1.0
287  40.20  12.80  1.0
288  40.20  14.80  1.0
289  40.40  12.05  1.0
290  40.45  12.50  1.0
291  40.45  14.50  1.0
292  40.60  15.25  1.0
293  40.65  14.90  1.0
294  40.70  16.45  1.0
295  40.95  15.70  1.0
296  40.95  17.05  1.0
297  41.25  16.80  1.0

[298 rows x 3 columns]

In [386]:
jumlahmodel = 20
array = np.arange(0,dftrain.shape[0])
random = np.random.randint(dftrain.shape[0], size=(jumlahmodel,30))
test = [i for i in array if i not in random]
print("Jumlah Sisa: ",len(test))
Xtrainrandom = []
Ytrainrandom = []
for i in range(jumlahmodel):
  Ytrainrandom.append(np.delete(train[random[i]], (0,1), axis=1)) 
  Xtrainrandom.append(np.delete(train[random[i]], 2, axis=1)) 
Xtrainrandom

Jumlah Sisa:  34


[array([[19.45, 19.05],
        [33.35,  7.45],
        [20.4 ,  7.  ],
        [36.1 ,  8.1 ],
        [26.85,  4.95],
        [14.75, 15.1 ],
        [24.05, 14.9 ],
        [17.35, 17.05],
        [16.65, 10.9 ],
        [37.25, 10.15],
        [33.6 ,  5.25],
        [38.95, 12.9 ],
        [17.5 ,  8.3 ],
        [19.4 ,  8.85],
        [36.  ,  9.65],
        [34.1 ,  5.  ],
        [15.15, 24.2 ],
        [ 2.9 , 21.15],
        [39.9 , 16.2 ],
        [36.6 ,  6.7 ],
        [29.5 ,  4.7 ],
        [29.25,  6.3 ],
        [29.2 ,  4.  ],
        [17.  , 15.65],
        [40.4 , 12.05],
        [20.55,  8.8 ],
        [24.7 ,  3.85],
        [35.05,  8.  ],
        [27.5 ,  5.45],
        [22.05, 20.25]]), array([[19.25, 18.7 ],
        [18.9 , 12.05],
        [20.5 ,  6.35],
        [23.5 , 15.2 ],
        [40.45, 14.5 ],
        [19.8 ,  9.95],
        [36.7 ,  9.15],
        [39.5 , 16.95],
        [39.5 , 11.8 ],
        [29.75,  3.45],
        [34.65,  5.65],
        [24.35,

In [388]:
objmodel = list()
for i in range(jumlahmodel):
    objmodel.append(GaussianNB().fit(Xtrainrandom[i],Ytrainrandom[i].ravel()))
objmodel

[GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09),
 GaussianNB(priors=None, var_smoothing=1e-09)]

In [389]:
Ytestsisa = np.delete(train[test], (0,1), axis=1)
Xtestsisa = np.delete(train[test], 2, axis=1)
Ytestpredict = []
for i in range(jumlahmodel):
  Ytestpredict.append(objmodel[i].predict(Xtestsisa))
  print("Akurasi Model {}: {}".format(i,np.mean(Ytestpredict[i] == Ytestsisa)))

Akurasi Model 0: 0.6089965397923875
Akurasi Model 1: 0.6211072664359861
Akurasi Model 2: 0.5847750865051903
Akurasi Model 3: 0.5847750865051903
Akurasi Model 4: 0.6089965397923875
Akurasi Model 5: 0.6211072664359861
Akurasi Model 6: 0.6089965397923875
Akurasi Model 7: 0.6211072664359861
Akurasi Model 8: 0.6089965397923875
Akurasi Model 9: 0.6089965397923875
Akurasi Model 10: 0.596885813148789
Akurasi Model 11: 0.6332179930795848
Akurasi Model 12: 0.6089965397923875
Akurasi Model 13: 0.6089965397923875
Akurasi Model 14: 0.6089965397923875
Akurasi Model 15: 0.6211072664359861
Akurasi Model 16: 0.6089965397923875
Akurasi Model 17: 0.6089965397923875
Akurasi Model 18: 0.6211072664359861
Akurasi Model 19: 0.6089965397923875


In [390]:
BaggingYtestpredict = []
for i in range(len(Ytestsisa)):
  votebagging = np.array(Ytestpredict)[:,i]
  votebagging = votebagging.astype(int)
  counts = np.bincount(votebagging)
  BaggingYtestpredict.append(np.argmax(counts))
print("Akurasi Model Bagging: {}".format(np.mean(BaggingYtestpredict == Ytestsisa)))

Akurasi Model Bagging: 0.6089965397923875


In [391]:
Ytestpredict

[array([2., 2., 2., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 1., 2., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 2., 2., 2., 2., 2., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1.,
        1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 2., 2., 2., 2., 2., 1., 1., 2., 1., 1., 1., 1., 2., 1., 1., 1.,
        1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 2., 2., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 1., 2., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 2., 1., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.]),
 array([2., 2., 2., 2., 2., 2., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,


In [392]:
BaggingYtestpredict

[2,
 2,
 2,
 2,
 2,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 2,
 1,
 2,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1,
 1]